"""added donated_amount column to User

Revision ID: 086275917325
Revises: 8478e42dc9ce
Create Date: 2023-02-24 04:20:09.679200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086275917325'
down_revision = '8478e42dc9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donated_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('donated_amount')

    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
