"""Initial migration.

Revision ID: 4fb45988d244
Revises: 
Create Date: 2023-02-24 13:00:01.110771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fb45988d244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=40), nullable=True))
        batch_op.drop_constraint('donation_record_ibfk_3', type_='foreignkey')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('donation_record_ibfk_3', 'donation_plan', ['plan_id'], ['id'])
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
