"""updated donationplan table

Revision ID: 5dac8f7dc8cc
Revises: 58371dab5755
Create Date: 2023-02-24 03:48:06.347745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dac8f7dc8cc'
down_revision = '58371dab5755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_plan', schema=None) as batch_op:
        batch_op.drop_constraint('donation_plan_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('donation_plan_ibfk_1', type_='foreignkey')
        batch_op.drop_column('amount_id')
        batch_op.drop_column('period_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('donation_plan_ibfk_1', 'donation_amount', ['amount_id'], ['id'])
        batch_op.create_foreign_key('donation_plan_ibfk_2', 'donation_period', ['period_id'], ['id'])

    # ### end Alembic commands ###
