"""updated DonationRecord

Revision ID: 8478e42dc9ce
Revises: 5dac8f7dc8cc
Create Date: 2023-02-24 03:51:43.962584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8478e42dc9ce'
down_revision = '5dac8f7dc8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donater_id', sa.Integer(), nullable=False))
        batch_op.alter_column('plan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('donation_record_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('donation_record_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['donater_id'], ['id'])
        batch_op.drop_column('amount_id')
        batch_op.drop_column('period_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('donation_record_ibfk_2', 'donation_period', ['period_id'], ['id'])
        batch_op.create_foreign_key('donation_record_ibfk_1', 'donation_amount', ['amount_id'], ['id'])
        batch_op.alter_column('plan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('donater_id')

    # ### end Alembic commands ###
