"""amount of record become int instead of relationshiop

Revision ID: 95dcfb0cc327
Revises: bc1dcb08d748
Create Date: 2023-02-24 05:28:18.754470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dcfb0cc327'
down_revision = 'bc1dcb08d748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_record', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
