"""added ProjectComment table

Revision ID: 96114255a790
Revises: 95dcfb0cc327
Create Date: 2023-02-24 10:05:00.042641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96114255a790'
down_revision = '95dcfb0cc327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_comment')
    # ### end Alembic commands ###
